### ISSUE TITLE
Update nuget-in-path

### ISSUE THREAD

**Issue by ncoden** [FezVrasta/nuget-publish#1]
This project rely on `nuget-in-path@2.0.1`, a fork of [node-nuget](https://github.com/kmalakoff/node-nuget). As `nuget-in-path` cannot receive issues, I'm submitting it here.

`node-nuget` recently published a new version `2.0.2` to resolve https://github.com/kmalakoff/node-nuget/issues/7. @FezVrasta Could you merge these changes into the fork and publish the new version ?

Thank you.

**Comment by FezVrasta** [comment]
Please feel free to send a PR over this repo, I'll merge it.
